/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TypesAffaireListeChoix: typeof import('./src/components/TypesAffaireListeChoix.vue')['default']
    UniteOrgChoix: typeof import('./src/components/UniteOrgChoix.vue')['default']
    UniteOrgNode: typeof import('./src/components/UniteOrgNode.vue')['default']
  }
}
